= MoreShapes
A procedural obj file generator

= Features
* UV and Normal Support
* Automatic 3 decimal precision and reuse of previous vertex, normals, and UV coords.
* Simple, extensible Lua-based api
* Great Curve support!

= Usage

`morecurves name_of_your_generator_file.lua``

Example run.lua:
....
add_triangle(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25)
export_mesh("test.obj")
....
Resulting file:
....
v 7 8 9
v 4 5 6
v 1 2 3
vt 23 24
vt 21 22
vt 19 20
vn 16 17 18
vn 13 14 15
vn 10 11 12
g 25
f 3/3/3 2/2/2 1/1/1 
....

NOTE: The link:lua_api/readme{outfilesuffix}[API Reference] comes with the code in `lua_api/readme.adoc`

= Compiling/Installing

TIP: https://github.com/ExeVirus/morecurves/releases[Prebuilt Windows Releases] are available here on github.

This is a CMAKE based, C++ project, with all dependencies included, and is fully cross platform.
Use your favorite CMAKE based methods or follow your systems-specific instructions:

= Linux
Sorry, I haven't filled this in yet

= Windows
Sorry, I haven't filled this in yet

= Mac
Sorry, I haven't filled this in yet



